### ISSUE TITLE
Selecting a crop causes page load error on mobile

### ISSUE THREAD

**Issue by cameronkruse** [earthrise-media/vacs-map#101]
**Current Behavior:** Selecting a crop from the comparison page causes the map explorer page to error while loading. On safari it reloads, but with African Eggplant which is the first crop alphabetically. On Chrome the page sometimes shows an error and sometimes loads African Eggplant instead of the chosen crop. It seems that sharing a link to a different crop and then visiting this link on mobile also causes these errors.

**Desired behavior:** selecting a crop from the comparison page it should load that crop in the map comparison tool.

**Comment by mwbernard** [comment]
Resolved in #109
