### ISSUE TITLE
Map tooltip anchored to screen not map on mobile

### ISSUE THREAD

**Issue by cameronkruse** [earthrise-media/vacs-map#102]
when a user clicks a dot on the map, the popup is fixed to a screen position not the map. If the user pans the map after clicking a dot, the dot moves away from the tooltip (see screenshot).

Desired behavior would be for the tooltip to anchor to the dot on the map like it does on desktop.
![IMG_0505](https://github.com/earthrise-media/vacs-map/assets/14115927/9473527f-06e0-4c07-b6db-9822a09eef3a)

**Comment by mwbernard** [comment]
@cameronkruse we're only ever pinning tooltips to mouse position on the screen, and the mobile interpretation of 'hover' as a touch is causing this. 

A quick solution would be giving the tooltip a fixed position (maybe near the bottom of the screen) on mobile? I get that its not ideal but seems better than a floating one that moves around. And the dots will still be highlighted to show which one you're looking at

**Comment by mwbernard** [comment]
Nope, no change to desktop behavior

**Comment by cameronkruse** [comment]
This seems like a good solution!
