### ISSUE TITLE
Mobile page reload bug

### ISSUE THREAD

**Issue by mwbernard** [earthrise-media/vacs-map#123]
When navigating to the explore page on mobile, the page reloads and can throw a browser reload error sometimes (often on Safari). Not totally sure what is causing this - It happens when navigating from the crop overview page, or just loading the page straight from a URL.

We have some components which try to access data, sometimes before its loaded - we might try handling these more smoothly at a high level (for example don't try to render anything on the sidebar until data is ready) and see if that helps. Its probably worth doing that anyway.

**Comment by mwbernard** [comment]
@ebrelsford tried connecting through Safari developer tools w/ wired connection to phone. I'm able to inspect the page etc. but I'm not seeing any console warnings or errors that seem related to the page reloading bug. Just a 'webpage crashed' message in the page title, but no console messages. Tested on both safari and chrome but just not yielding much info.

Once or twice I got a warning regarding not having mapbox css styles loaded, but we do have those imported in the app, and that warning wasn't consistent so I don't think that's it.

**Comment by ebrelsford** [comment]
@mwbernard Thanks for the update! Can you see any metrics around performance before the crash? Such as amount of memory in use or the length of time network requests are taking?

**Comment by mwbernard** [comment]
@ebrelsford  This is a recording of loading the explore page. From what I can tell around the 8s mark the page automatically reloads and the crash seems to happen then, or right after that automatic reload gets triggered for some reason. The inspector also kind of crashes, or disconnects, when the page reloads though and I keep having to re-inspect the new page - so I'm not convinced this is fully tracking what's happening

<img width="1353" alt="Screenshot 2023-12-12 at 3 14 17 PM" src="https://github.com/earthrise-media/vacs-map/assets/25800091/8b60a5f6-7421-4c66-8c18-95cbfced9cae">

**Comment by ebrelsford** [comment]
@mwbernard I'll have a fix soon, I believe I've isolated the issue to the grid data and how it gets joined.
