### ISSUE TITLE
Design d3 map for home page / crop cards

### ISSUE THREAD

**Issue by mwbernard** [earthrise-media/vacs-map#26]
I think the easiest way to go about this might be in Observable.

I have [a notebook here](https://observablehq.com/d/749183f02ac03d2b?collection=@stamen/earth-genome) that transitions through crops on top of a projected d3 map. 

@kelsey-taylor would it be okay for you to do a first pass at the map design in the notebook, and then I'll implement that in the app for the home page and also in the script that we'll use to generate the cards? Updating it later is easy, but just want a starting point! 

Also... the map example was one I found on observable, so if there are different geo files we should be using, or you'd like to change the map data at all let me know!

**Comment by kelsey-taylor** [comment]
sounds good, i'm on it!

**Comment by kelsey-taylor** [comment]
ok these are done in observable and ready for ya @mwbernard!
