### ISSUE TITLE
Add soil carbon and sand raster data to map

### ISSUE THREAD

**Issue by kelsey-taylor** [earthrise-media/vacs-map#7]
Cameron shared this data with us [here](https://stamen.slack.com/archives/C0612UGUC7R/p1699427466205919) 

We've talked internally about having one or both of these layers as part of the basemap on the explore view and the crop profile page

**Comment by ebrelsford** [comment]
Should be pretty straightforward with #17 in

**Comment by ebrelsford** [comment]
@kelsey-taylor adding the [raster layers like this](https://earthrise-media.github.io/vacs-map/raster.html#4.13/2.31/19.6) will be sufficient right?

**Comment by kelsey-taylor** [comment]
yep should be!

**Comment by ebrelsford** [comment]
Closed by #31
