### ISSUE TITLE
Make spatial data filterable by crop property

### ISSUE THREAD

**Issue by kelsey-taylor** [earthrise-media/vacs-map#9]
It'll be important for us to be able to filter the spatial data by crop properties (ex. drought tolerance, crop group, iron levels, etc.) for a few of the screens we're envisioning

**Comment by mwbernard** [comment]
@kelsey-taylor I'm a little confused here, what do we want to do / for which features?

**Comment by kelsey-taylor** [comment]
this ticket isn't very descriptive 😬  but it means adding these features:

<img width="741" alt="Screenshot 2023-11-21 at 10 58 43 AM" src="https://github.com/earthrise-media/vacs-map/assets/57634568/e6072e8f-f134-4c9d-977b-f4e73fd5722f">

**Comment by kelsey-taylor** [comment]
blocked by #46

**Comment by kelsey-taylor** [comment]
sounds like we're going to start on this with the data we have, then update with the complete data later — moving to to-do
