### ISSUE TITLE
Adjust fingerprint layout when there's vertical space

### ISSUE THREAD

**Issue by mwbernard** [earthrise-media/vacs-map#93]
Think we can do something simple like bumping the legend below to take advantage of the space and have the fingerprint be a bit larger

![Screenshot 2023-11-30 at 9 39 27 AM](https://github.com/earthrise-media/vacs-map/assets/25800091/ca400b46-4a21-4136-90d2-28584a210778)

**Comment by cgcarter25** [comment]
I like the idea of the minimum height! feels the most natural to me, but down for either

**Comment by kelsey-taylor** [comment]
i like the idea of sliding it either above or below the line charts — since the legend applies to both the charts and the map, either makes sense to me

**Comment by mwbernard** [comment]
In agmip meeting Jose shared his screen (small macbook) that had the legend and much of the sidebar cut off in explore mode without any scrolling available - gotta check that
